name: Fetch Speedrun Data

on:
  schedule:
    - cron: "0 0 * * 0" # Runs every Sunday at midnight
  workflow_dispatch: # Allows manual trigger

jobs:
  fetch-and-store:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies
        run: npm install axios

      - name: Fetch Speedrun Data with Exponential Backoff
        run: |
          node -e "
          const fs = require('fs');
          const axios = require('axios');
          const leaderboardUrls = require('./src/assets/leaderboardUrls.jsx'); // Import your URLs

          // Exponential backoff logic
          const fetchDataWithBackoff = async (url, retries = 5, delay = 1000) => {
            for (let i = 0; i <= retries; i++) {
              try {
                const response = await axios.get(url);
                return response.data;
              } catch (error) {
                if (i < retries && error.response?.status === 420) {
                  console.log(\`Rate limit hit on \${url}. Retrying in \${delay}ms...\`);
                  await new Promise(res => setTimeout(res, delay));
                  delay *= 2; // Double the delay for exponential backoff
                } else {
                  console.error(\`Failed to fetch \${url}: \${error.message}\`);
                  return { error: error.message }; // Return error if retries exhausted
                }
              }
            }
          };

          const fetchAllData = async () => {
            const results = {};
            for (const { url } of leaderboardUrls) {
              console.log(\`Fetching data from: \${url}\`);
              const data = await fetchDataWithBackoff(url);
              results[url] = data;
            }
            fs.writeFileSync('data/speedrunData.json', JSON.stringify(results, null, 2));
            console.log('Data successfully written to data/speedrunData.json');
          };

          fetchAllData();
          "

      - name: Commit and Push Data
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/speedrunData.json
          git commit -m "Update Speedrun Data [ci skip]" || echo "No changes to commit"
          git push
